load vectors

fmod POSE is
  pr VECTOR3 .
  sort Pose .
  --- position and euler angles, in degrees
  op {posi:_,rota:_} : Vector3 Vector3 -> Pose [ctor] .

  vars V V2 V3 V4 P P2 : Vector3 .
  vars X Y Z : Float .
  op position : Pose -> Vector3 .
  op yawAngle : Pose -> Float . --- Euler angle over Yaw-axis
  eq position({posi: P, rota: V}) = P .
  eq yawAngle({posi: P, rota: X Y Z}) = Z .
endfm

fmod TWIST is
  pr VECTOR3 .
  sort Twist .
  --- linear and angular
  op {lin:_,ang:_} : Vector3 Vector3 -> Twist [ctor] .

  vars V V2 V3 V4 P P2 : Vector3 .
  vars X Y Z : Float .
  op linear : Twist -> Vector3 .
  op angular : Twist -> Vector3 .
  eq linear({lin: V, ang: V2}) = V .
  eq angular({lin: V, ang: V2}) = V2 .
endfm

fmod GROUND-TRUTH-EGO is 
  pr POSE + TWIST .
  sort GTEgo .
  op {pose:_,twist:_,accel:_} : Pose Twist Twist -> GTEgo [ctor] .

  vars TWIST ACCEL TWIST2 ACCEL2 : Twist .
  var POSE : Pose .
  vars X Y Z : Float .
  var OBJ : GTEgo .

  op gtPose : GTEgo -> Pose .
  op gtVel : GTEgo -> Twist .
  op gtAccel : GTEgo -> Vector3 .

  --- alias
  op gtPosition : GTEgo -> Vector3 .
  op gtYawAngle : GTEgo -> Float .
  op gtLinearVel : GTEgo -> Vector3 .

  eq gtPose({pose: POSE, twist: TWIST, accel: ACCEL}) = POSE .
  eq gtVel({pose: POSE, twist: TWIST, accel: ACCEL}) = TWIST .
  eq gtAccel({pose: POSE, twist: TWIST, accel: ACCEL}) = linear(ACCEL) .

  eq gtPosition(OBJ) = position(gtPose(OBJ)) .
  eq gtYawAngle(OBJ) = yawAngle(gtPose(OBJ)) .
  eq gtLinearVel(OBJ) = linear(gtVel(OBJ)) .
endfm

fmod GROUND-TRUTH-VEHICLE is 
  pr POSE + TWIST + STRING + RECT .
  sort GTVehicle .
  op {name:_,pose:_,twist:_,accel:_,gt-rect:_} : String Pose Twist Float Rect -> GTVehicle [ctor] .

  vars TWIST ACCEL TWIST2 ACCEL2 : Twist .
  var POSE : Pose .
  vars X Y Z : Float .
  vars STR STR2 : String .
  var RECT : Rect .
  var OBJ : GTVehicle .

  op name : GTVehicle -> String .
  op gtPose : GTVehicle -> Pose .
  op gtVel : GTVehicle -> Twist .
  op gtAccel : GTVehicle -> Vector3 .
  op gtRectOnCamera : GTVehicle -> Rect .

  --- alias
  op gtPosition : GTVehicle -> Vector3 .
  op gtYawAngle : GTVehicle -> Float .
  op gtLinearVel : GTVehicle -> Vector3 .

  eq name({name: STR, pose: POSE, twist: TWIST, accel: X, gt-rect: RECT}) = STR .
  eq gtPose({name: STR, pose: POSE, twist: TWIST, accel: X, gt-rect: RECT}) = POSE .
  eq gtVel({name: STR, pose: POSE, twist: TWIST, accel: X, gt-rect: RECT}) = TWIST .
  eq gtAccel({name: STR, pose: POSE, twist: TWIST, accel: X, gt-rect: RECT}) = X 0.0 0.0 .

  eq gtRectOnCamera({name: STR, pose: POSE, twist: TWIST, accel: X, gt-rect: RECT}) = RECT .
  eq gtPosition(OBJ) = position(gtPose(OBJ)) .
  eq gtYawAngle(OBJ) = yawAngle(gtPose(OBJ)) .
  eq gtLinearVel(OBJ) = linear(gtVel(OBJ)) .
endfm

fmod CLASSIFICATION is
  pr FLOAT + NAT .
  sort Class .
  --- class ID and probability
  op _->_ : Nat Float -> Class [ctor] .
endfm

view Class from TRIV to CLASSIFICATION is
  sort Elt to Class .
endv 
fmod CLASS-SET is 
  pr SET{Class} .

  vars X Y Z : Float .
  vars CLS : Set{Class} .
  var N : Nat .
  
  --- check if vehicle is detected in classification 
  op isVehicleClass : Set{Class} -> Bool .
  ceq isVehicleClass((N -> X, CLS)) = true
    if N <= VEHICLE-CLASS-MAX /\ N >= VEHICLE-CLASS-MIN /\
       X >= CLASSIFICATION-THRESHOLD .
  eq isVehicleClass(CLS) = false [owise] .

  --- check if pedestrian is detected in classification 
  op isPedestrianClass : Set{Class} -> Bool .
  ceq isPedestrianClass((N -> X, CLS)) = true
    if N == PEDESTRIAN-CLASS /\
       X >= CLASSIFICATION-THRESHOLD .
  eq isPedestrianClass(CLS) = false [owise] .

***(
 * constants
)
  ops UNKNOW-CLASS PEDESTRIAN-CLASS VEHICLE-CLASS-MIN VEHICLE-CLASS-MAX : -> Nat .
  eq UNKNOW-CLASS = 0 .
  eq PEDESTRIAN-CLASS = 7 .
  eq VEHICLE-CLASS-MIN = 1 .
  eq VEHICLE-CLASS-MAX = 6 .
  op CLASSIFICATION-THRESHOLD : -> Float .
  eq CLASSIFICATION-THRESHOLD = 0.1 .
endfm

fmod PERCEPTION-OBJECT-SHAPE is
  pr LIST{Vector3} .
  sort PShape .
  op box-shape : Vector3 -> PShape [ctor] .
  op polygon-shape : List{Vector3} -> PShape [ctor] .
endfm

--- perceived objects
fmod PERCEPTION-OBJECT is
  pr POSE + TWIST + CLASS-SET + RECT + PERCEPTION-OBJECT-SHAPE + VECTOR3-AND-NULL + STRING .
  --- pr LIST{PredictPath} . TODO
  sort PObject .

  op {id:_,epro:_,class:[_],pose:_,twist:_,accel:_,shape:_} : 
    String Float Set{Class} Pose Twist Twist PShape -> PObject [ctor] .

  vars TWIST ACCEL TWIST2 ACCEL2 : Twist .
  var POSE : Pose .
  vars PROB : Float .
  var RECT : Rect .
  var UUID : String .
  var CLS : Set{Class} .
  var OBJ : PObject .
  var SH : PShape .

  op pose : PObject -> Pose .
  op velocity : PObject -> Twist .
  op class : PObject -> Set{Class} .
  op epro : PObject -> Float .
  op position : PObject -> Vector3 .

  --- aliases
  op yawAngle : PObject -> Float .
  op linearVel : PObject -> Vector3 .
  op shape : PObject -> PShape .

  eq pose({id: UUID, epro: PROB, class: [CLS], pose: POSE, twist: TWIST, accel: ACCEL, shape: SH}) = POSE .
  eq velocity({id: UUID, epro: PROB, class: [CLS], pose: POSE, twist: TWIST, accel: ACCEL, shape: SH}) = TWIST .
  eq class({id: UUID, epro: PROB, class: [CLS], pose: POSE, twist: TWIST, accel: ACCEL, shape: SH}) = CLS .
  eq epro({id: UUID, epro: PROB, class: [CLS], pose: POSE, twist: TWIST, accel: ACCEL, shape: SH}) = PROB .
  eq shape({id: UUID, epro: PROB, class: [CLS], pose: POSE, twist: TWIST, accel: ACCEL, shape: SH}) = SH .

  eq position(OBJ) = position(pose(OBJ)) .
  eq yawAngle(OBJ) = yawAngle(pose(OBJ)) .
  eq linearVel(OBJ) = linear(velocity(OBJ)) .
endfm

--- perceived objects by camera
fmod BOUNDING-BOX-PERCEPTION-OBJECT is
  pr CLASS-SET + RECT .
  sort BBPObject .
  op {epro:_,class:[_],bb-rect:_} : Float Set{Class} Rect -> BBPObject [ctor] .
  vars PROB : Float .
  var RECT : Rect .
  var CLS : Set{Class} .
  var OBJ : BBPObject .

  op class : BBPObject -> Set{Class} .
  op epro : BBPObject -> Float .
  op bbRect : BBPObject -> Rect .

  eq class({epro: PROB, class: [CLS], bb-rect: RECT}) = CLS .
  eq epro({epro: PROB, class: [CLS], bb-rect: RECT}) = PROB .
  eq bbRect({epro: PROB, class: [CLS], bb-rect: RECT}) = RECT .
endfm