"""Validated input profile for a single dynamics U-turn execution."""

from __future__ import annotations

import math
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping

from scenario_specs.uturn import (
    JAMA_PROFILES,
    resolve_awsim_npc_start_speed_ratio,
    validate_sampled_parameters,
)

from .calibration import (
    AUTOWARE171_UTURN_CONTROLLER_KIND,
    load_autoware171_uturn_braking_profile,
    load_autoware171_uturn_screening_margin,
    predict_autoware171_uturn_start_geometry,
)
from .models.uturn import UTurnODEConfig, VehicleState
from .models.uturn_sde import UTurnSDEConfig, UTurnSDENoise


# The AWSIM scenario constructs a half circle from the NPC front centre to the
# projection on lane 511.  This value is half the endpoint distance in an
# actual autoware171 trace generated by that code (12 x 15 degree waypoints).
# It is a calibrated local-geometry approximation, not a replacement for the
# Lanelet map or the AWSIM vehicle controller.
AWSIM_UTURN_RADIUS_M = 4.85545500111187
AWSIM_ALIGNMENT_MODE = "uturn_trigger_aligned"
AWSIM_GEOMETRY_PROVENANCE = "awsim_autoware171_trace_sim7043_waypoints"
AWSIM_VEHICLE_GEOMETRY_M = {
    "ego": {"length": 4.886, "width": 2.186},
    "npc": {"length": 4.64, "width": 1.94},
}


@dataclass(frozen=True)
class DynamicsExecutionProfile:
    model_id: str
    solver_kind: str
    ode_config: UTurnODEConfig
    sde_config: UTurnSDEConfig | None
    output_root: Path
    collision_distance_m: float
    collision_model: str
    vehicle_geometry_m: dict[str, dict[str, float]]
    controller_kind: str
    controller_provenance: dict[str, object]
    geometry_provenance: dict[str, object]
    alignment_mode: str
    screening_clearance_margin_m: float
    screening_provenance: dict[str, object]
    source_input: dict[str, object]

    def to_meta(self) -> dict[str, object]:
        meta: dict[str, object] = {
            "model_id": self.model_id,
            "solver_kind": self.solver_kind,
            "collision_distance_m": self.collision_distance_m,
            "collision_model": self.collision_model,
            "ttc_model": (
                "cvm_obb_dt0.1_horizon5"
                if self.collision_model == "obb"
                else "radial_center_distance"
            ),
            "vehicle_geometry_m": self.vehicle_geometry_m,
            "controller_kind": self.controller_kind,
            "controller_provenance": self.controller_provenance,
            "horizon_sec": self.ode_config.horizon_sec,
            "max_step_sec": self.ode_config.max_step_sec,
            "jama_profile": dict(self.ode_config.jama_profile),
            "alignment_mode": self.alignment_mode,
            "screening_clearance_margin_m": self.screening_clearance_margin_m,
            "screening_provenance": self.screening_provenance,
            "geometry_provenance": self.geometry_provenance,
            "resolved_initial_state": {
                "ego": dict(vars(self.ode_config.ego_initial)),
                "npc": dict(vars(self.ode_config.npc_initial)),
            },
            "resolved_npc_start_speed_ratio": self.ode_config.npc_start_speed_ratio,
            "resolved_turn_radius_m": self.ode_config.turn_radius_m,
            "resolved_turn_angle_rad": self.ode_config.turn_angle_rad,
            "resolved_npc_turn_reference_offset_m": self.ode_config.npc_turn_reference_offset_m,
            "resolved_longitudinal_clearance_offset_m": (
                self.ode_config.longitudinal_clearance_offset_m
            ),
        }
        if self.sde_config is not None:
            zero_noise = all(
                float(value) == 0.0
                for value in vars(self.sde_config.noise).values()
            )
            meta["sde_seed"] = self.sde_config.seed
            meta["sde_dt_sec"] = self.sde_config.dt_sec
            meta["sde_noise"] = dict(vars(self.sde_config.noise))
            meta["effective_solver_kind"] = "ode" if zero_noise else "sde"
            meta["zero_noise_reduction"] = zero_noise
        else:
            meta["effective_solver_kind"] = "ode"
        return meta


def build_execution_profile(
    inputs: Mapping[str, object],
    *,
    default_output_root: str | Path,
) -> DynamicsExecutionProfile:
    model_id = str(inputs.get("model_id", "uturn"))
    if model_id != "uturn":
        raise ValueError(f"Unsupported dynamics model_id: {model_id!r}")

    sampled = {
        key: _required_float(inputs, key)
        for key in ("dx0", "ego_speed", "npc_speed")
    }
    validate_sampled_parameters(sampled)
    ego_target_speed_mps = sampled["ego_speed"] / 3.6
    npc_target_speed_mps = sampled["npc_speed"] / 3.6

    alignment_mode = str(inputs.get("alignment_mode", AWSIM_ALIGNMENT_MODE))
    if alignment_mode not in {AWSIM_ALIGNMENT_MODE, "legacy_generic"}:
        raise ValueError(
            "alignment_mode must be 'uturn_trigger_aligned' or 'legacy_generic'"
        )

    if alignment_mode == AWSIM_ALIGNMENT_MODE:
        calibrated_geometry, geometry_provenance = (
            predict_autoware171_uturn_start_geometry(**sampled)
        )
    else:
        calibrated_geometry = {
            "longitudinal_center_m": sampled["dx0"] + 15.0,
            "lateral_center_m": 0.0,
            "ego_speed_mps": ego_target_speed_mps,
            "npc_speed_mps": npc_target_speed_mps,
            "npc_heading_rad": math.pi,
            "turn_radius_m": 10.0,
            "turn_angle_rad": math.pi,
        }
        geometry_provenance = {"source": "legacy_generic_defaults"}
    vehicle_geometry_m = _resolve_vehicle_geometry(inputs)
    initial = _mapping(inputs.get("initial_state"), name="initial_state")
    default_turn_radius_m = (
        calibrated_geometry["turn_radius_m"]
        if alignment_mode == AWSIM_ALIGNMENT_MODE
        else 10.0
    )
    turn_radius_m = _optional_float(
        inputs, "turn_radius_m", default=default_turn_radius_m
    )
    turn_angle_rad = _optional_float(
        inputs, "turn_angle_rad", default=calibrated_geometry["turn_angle_rad"]
    )
    initial_gap_m = _optional_float(
        inputs,
        "initial_gap_m",
        default=(
            calibrated_geometry["longitudinal_center_m"] - sampled["dx0"]
            if alignment_mode == AWSIM_ALIGNMENT_MODE
            else 15.0
        ),
    )
    longitudinal_clearance_offset_m = (
        initial_gap_m if alignment_mode == AWSIM_ALIGNMENT_MODE else 0.0
    )
    lane_offset_m = _optional_float(
        inputs,
        "lane_offset_m",
        default=(
            calibrated_geometry["lateral_center_m"]
            if alignment_mode == AWSIM_ALIGNMENT_MODE
            else 0.0
        ),
    )
    ego_initial = _vehicle_state(
        initial.get("ego"),
        default=VehicleState(
            0.0,
            0.0,
            0.0,
            calibrated_geometry["ego_speed_mps"],
        ),
        name="initial_state.ego",
    )
    npc_initial = _vehicle_state(
        initial.get("npc"),
        default=VehicleState(
            sampled["dx0"] + initial_gap_m,
            lane_offset_m,
            calibrated_geometry["npc_heading_rad"],
            calibrated_geometry["npc_speed_mps"],
        ),
        name="initial_state.npc",
    )

    jama_profile_name = str(inputs.get("jama_profile", "ai_aeb"))
    try:
        jama_profile = dict(JAMA_PROFILES[jama_profile_name])
    except KeyError as exc:
        raise ValueError(f"Unsupported JAMA profile: {jama_profile_name!r}") from exc
    controller_kind = str(inputs.get("controller_kind", f"jama_{jama_profile_name}"))
    if controller_kind == AUTOWARE171_UTURN_CONTROLLER_KIND:
        braking_profile, controller_provenance = (
            load_autoware171_uturn_braking_profile()
        )
    elif controller_kind in {"jama_ai_aeb", "jama_human"}:
        expected_profile = controller_kind.removeprefix("jama_")
        if jama_profile_name != expected_profile:
            raise ValueError(
                f"controller_kind={controller_kind!r} conflicts with "
                f"jama_profile={jama_profile_name!r}"
            )
        braking_profile = jama_profile
        controller_provenance = {"source": "scenario_specs.uturn.JAMA_PROFILES"}
    else:
        raise ValueError(f"Unsupported dynamics controller_kind: {controller_kind!r}")

    ode_config = UTurnODEConfig(
        ego_initial=ego_initial,
        npc_initial=npc_initial,
        dx0_m=sampled["dx0"],
        ego_target_speed_mps=ego_target_speed_mps,
        npc_target_speed_mps=npc_target_speed_mps,
        longitudinal_clearance_offset_m=longitudinal_clearance_offset_m,
        ego_cruise_acceleration_mps2=_optional_float(
            inputs, "ego_cruise_acceleration_mps2", default=0.0
        ),
        npc_acceleration_mps2=_optional_float(
            inputs, "npc_acceleration_mps2", default=7.0
        ),
        npc_start_speed_ratio=_optional_float(
            inputs,
            "npc_start_speed_ratio",
            default=resolve_awsim_npc_start_speed_ratio(
                ego_speed=sampled["ego_speed"]
            ),
        ),
        turn_radius_m=turn_radius_m,
        turn_angle_rad=turn_angle_rad,
        npc_turn_reference_offset_m=_optional_float(
            inputs,
            "npc_turn_reference_offset_m",
            default=(
                float(geometry_provenance["vehicle_center_offsets_m"]["npc_x"])
                if alignment_mode == AWSIM_ALIGNMENT_MODE
                else 0.0
            ),
        ),
        turn_direction=_optional_float(inputs, "turn_direction", default=-1.0),
        horizon_sec=_optional_float(inputs, "horizon_sec", default=10.0),
        max_step_sec=_optional_float(inputs, "max_step_sec", default=0.02),
        jama_profile=braking_profile,
    )
    ode_config.validate()

    solver_kind = str(inputs.get("solver_kind", "ode"))
    if solver_kind not in {"ode", "sde"}:
        raise ValueError("solver_kind must be 'ode' or 'sde'")
    sde_config = None
    if solver_kind == "sde":
        noise = _mapping(inputs.get("sde_noise"), name="sde_noise")
        sde_config = UTurnSDEConfig(
            ode_config=ode_config,
            seed=_required_int(inputs, "sde_seed"),
            dt_sec=_optional_float(inputs, "sde_dt_sec", default=ode_config.max_step_sec),
            noise=UTurnSDENoise(
                npc_acceleration_std=_optional_float(noise, "npc_acceleration_std", default=0.0),
                ego_brake_acceleration_std=_optional_float(noise, "ego_brake_acceleration_std", default=0.0),
                npc_heading_std_rad_per_sqrt_sec=_optional_float(noise, "npc_heading_std_rad_per_sqrt_sec", default=0.0),
            ),
        )
        sde_config.validate()

    collision_distance_m = _optional_float(
        inputs, "collision_distance_m", default=4.5
    )
    if collision_distance_m <= 0.0:
        raise ValueError("collision_distance_m must be positive")
    collision_model = str(inputs.get("collision_model", "obb"))
    if collision_model not in {"obb", "center_distance"}:
        raise ValueError("collision_model must be 'obb' or 'center_distance'")
    calibrated_margin_m, screening_provenance = load_autoware171_uturn_screening_margin()
    screening_clearance_margin_m = _optional_float(
        inputs, "screening_clearance_margin_m", default=calibrated_margin_m
    )
    if screening_clearance_margin_m < 0.0:
        raise ValueError("screening_clearance_margin_m must be non-negative")
    if screening_clearance_margin_m != calibrated_margin_m:
        screening_provenance = {"source": "input_override"}
    else:
        # The margin was fitted against AWSIM with the Autoware-calibrated
        # controller; with other controllers it is only a geometric threshold.
        screening_provenance = {
            **screening_provenance,
            "calibrated_for_current_controller": (
                controller_kind == screening_provenance["calibrated_for_controller_kind"]
            ),
        }
    output_root = Path(
        str(inputs.get("output_root", default_output_root))
    ).expanduser().resolve()
    return DynamicsExecutionProfile(
        model_id=model_id,
        solver_kind=solver_kind,
        ode_config=ode_config,
        sde_config=sde_config,
        output_root=output_root,
        collision_distance_m=collision_distance_m,
        collision_model=collision_model,
        vehicle_geometry_m=vehicle_geometry_m,
        controller_kind=controller_kind,
        controller_provenance=controller_provenance,
        geometry_provenance=geometry_provenance,
        alignment_mode=alignment_mode,
        screening_clearance_margin_m=screening_clearance_margin_m,
        screening_provenance=screening_provenance,
        source_input={str(key): value for key, value in inputs.items()},
    )


def _mapping(value: object | None, *, name: str) -> Mapping[str, object]:
    if value is None:
        return {}
    if not isinstance(value, Mapping):
        raise ValueError(f"{name} must be a mapping")
    return value


def _resolve_vehicle_geometry(
    inputs: Mapping[str, object],
) -> dict[str, dict[str, float]]:
    geometry = {
        "ego": {
            "length": _optional_float(
                inputs,
                "ego_length_m",
                default=AWSIM_VEHICLE_GEOMETRY_M["ego"]["length"],
            ),
            "width": _optional_float(
                inputs,
                "ego_width_m",
                default=AWSIM_VEHICLE_GEOMETRY_M["ego"]["width"],
            ),
        },
        "npc": {
            "length": _optional_float(
                inputs,
                "npc_length_m",
                default=AWSIM_VEHICLE_GEOMETRY_M["npc"]["length"],
            ),
            "width": _optional_float(
                inputs,
                "npc_width_m",
                default=AWSIM_VEHICLE_GEOMETRY_M["npc"]["width"],
            ),
        },
    }
    if any(
        dimension <= 0.0
        for vehicle in geometry.values()
        for dimension in vehicle.values()
    ):
        raise ValueError("vehicle dimensions must be positive")
    return geometry


def _vehicle_state(
    value: object | None,
    *,
    default: VehicleState,
    name: str,
) -> VehicleState:
    if value is None:
        return default
    mapping = _mapping(value, name=name)
    return VehicleState(
        x_m=_optional_float(mapping, "x_m", default=default.x_m),
        y_m=_optional_float(mapping, "y_m", default=default.y_m),
        heading_rad=_optional_float(
            mapping, "heading_rad", default=default.heading_rad
        ),
        speed_mps=_optional_float(mapping, "speed_mps", default=default.speed_mps),
    )


def _required_float(values: Mapping[str, object], key: str) -> float:
    if key not in values:
        raise ValueError(f"Missing dynamics input: {key}")
    return _optional_float(values, key, default=float("nan"))


def _required_int(values: Mapping[str, object], key: str) -> int:
    if key not in values:
        raise ValueError(f"Missing dynamics input: {key}")
    value = values[key]
    if isinstance(value, bool):
        raise ValueError(f"Invalid integer dynamics input: {key}")
    try:
        parsed = int(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"Invalid integer dynamics input: {key}") from exc
    if str(parsed) != str(value).strip() and not isinstance(value, int):
        raise ValueError(f"Invalid integer dynamics input: {key}")
    return parsed


def _optional_float(values: Mapping[str, object], key: str, *, default: float) -> float:
    try:
        value = float(values.get(key, default))
    except (TypeError, ValueError) as exc:
        raise ValueError(f"Invalid numeric dynamics input: {key}") from exc
    if not math.isfinite(value):
        raise ValueError(f"Invalid numeric dynamics input: {key}")
    return value


__all__ = [
    "AWSIM_ALIGNMENT_MODE",
    "AWSIM_GEOMETRY_PROVENANCE",
    "AWSIM_UTURN_RADIUS_M",
    "AWSIM_VEHICLE_GEOMETRY_M",
    "DynamicsExecutionProfile",
    "build_execution_profile",
]
