from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Sequence


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Read a BBSL confidence-gap result JSON and print a human-readable "
            "summary without re-running FT4D."
        )
    )
    parser.add_argument(
        "result_json",
        help="Path to bbsl_confidence_gap_*.json generated by the v2 CLI.",
    )
    return parser


def load_payload(result_json: str | Path) -> dict[str, Any]:
    path = Path(result_json).expanduser().resolve()
    payload = json.loads(path.read_text(encoding="utf-8"))
    payload["_result_path"] = str(path)
    return payload


def render_confidence_gap_summary(payload: dict[str, Any]) -> str:
    confidence_summary = payload.get("confidence_summary", {})
    completion_summary = payload.get("completion_summary", {})

    lines = ["=" * 60]
    lines.append("AWSIM_launch BBSL confidence-gap summary")
    lines.append(f"target repo    : {payload.get('target_repo', '')}")
    lines.append(f"execution mode : {payload.get('execution_mode', '')}")
    lines.append(f"condition policy: {payload.get('condition_policy', '')}")
    lines.append(f"run mode       : {payload.get('run_mode', '')}")
    lines.append(f"tree mode      : {payload.get('tree_mode', '')}")
    lines.append(
        f"underconfident : {confidence_summary.get('underconfident_unique_count', '')}"
    )
    lines.append(
        f"total events   : {confidence_summary.get('total_unique_events', '')}"
    )
    lines.append(f"complete       : {completion_summary.get('complete', '')}")
    min_confidence = completion_summary.get("min_confidence")
    if isinstance(min_confidence, (int, float)):
        lines.append(f"min confidence : {min_confidence:.5f}")
    else:
        lines.append(f"min confidence : {min_confidence}")
    lines.append(f"total trials   : {completion_summary.get('total_trials', '')}")
    lines.append(f"result json    : {payload.get('_result_path', '')}")

    underconfident_events = confidence_summary.get("underconfident_events", [])
    if underconfident_events:
        lines.append("")
        lines.append("--- Underconfident Events ---")
        for event in underconfident_events[:10]:
            lines.append(
                "  ".join(
                    [
                        f"node={event.get('node_id', '')}",
                        f"event={event.get('event_id', '')}",
                        f"sigma_pe={event.get('sigma_pe', '')}",
                        f"trials={event.get('trials', '')}",
                        f"confidence={event.get('confidence', '')}",
                    ]
                )
            )
    lines.append("=" * 60)
    return "\n".join(lines)


def run_confidence_gap_summary(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(list(argv) if argv is not None else None)
    payload = load_payload(args.result_json)
    print(render_confidence_gap_summary(payload))
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    return run_confidence_gap_summary(argv)


if __name__ == "__main__":
    raise SystemExit(main())
