fmod MAYBE{X :: TRIV} is
  sort Maybe{X} .
  subsort X$Elt < Maybe{X} .
  op maybe{X} : -> Maybe{X} [ctor] .
endfm

fmod VECTOR3 is 
  pr FLOAT .
  sort Vector3 .
  op ___ : Float Float Float -> Vector3 [ctor] .

  op _-_ : Vector3 Vector3 -> Vector3 [prec 33 gather (E e)] .
  op _+_ : Vector3 Vector3 -> Vector3 [assoc comm prec 33] .
  op _*_ : Float Vector3 -> Vector3 [prec 31] .
  op magnitude : Vector3 -> Float .
  op distance : Vector3 Vector3 -> Float .
  op magnitudeIgnoreZ : Vector3 -> Float .
  op distanceIgnoreZ : Vector3 Vector3 -> Float .
  op ignoreZ : Vector3 -> Vector3 .
  op normalize : Vector3 -> Vector3 .
  op dot : Vector3 Vector3 -> Float .
  ops x y z : Vector3 -> Float .
  
  vars X Y Z X2 Y2 Z2 S : Float .
  vars V V2 : Vector3 .
  eq x(X Y Z) = X .
  eq y(X Y Z) = Y .
  eq z(X Y Z) = Z .
  eq ((X Y Z) + (X2 Y2 Z2)) = (X + X2) (Y + Y2) (Z + Z2) .
  eq ((X Y Z) - (X2 Y2 Z2)) = (X - X2) (Y - Y2) (Z - Z2) .
  eq (S * (X Y Z)) = (S * X  S * Y  S * Z) .
  eq dot((X Y Z) , (X2 Y2 Z2)) = (X * X2) + (Y * Y2) + (Z * Z2) .
  eq magnitude(X Y Z) = sqrt(X * X + Y * Y + Z * Z) .
  eq distance(V, V2) = magnitude(V - V2) .
  eq magnitudeIgnoreZ(X Y Z) = sqrt(X * X + Y * Y) .
  eq distanceIgnoreZ(V, V2) = magnitudeIgnoreZ(V - V2) .
  eq ignoreZ(X Y Z) = (X Y 0.0) .
  ceq normalize(X Y Z) = (X / S) (Y / S) (Z / S) 
    if S := magnitude(X Y Z) .

  op infiniteF : -> Float .
  eq infiniteF = 1.0e10 .

  --- helper functions
  op degreeToRadian : Float -> Float .
  op radianToDegree : Float -> Float .
  eq degreeToRadian(X) = (X / 180.0) * pi .
  eq radianToDegree(X) = (X * 180.0) / pi .

endfm

view Vector3 from TRIV to VECTOR3 is
  sort Elt to Vector3 .
endv
--- view Float from TRIV to FLOAT is
---   sort Elt to Float .
--- endv
fmod FLOAT-AND-NULL is
  pr MAYBE{Float} * (op maybe{Float} to nullFloat) .
endfm

fmod VECTOR3-AND-NULL is
  pr FLOAT-AND-NULL .
  pr MAYBE{Vector3} * (op maybe{Vector3} to nullVector3) .
  ops magnitude magnitudeIgnoreZ : Maybe{Vector3} -> Maybe{Float} .
  eq magnitude(nullVector3) = nullFloat .
  eq magnitudeIgnoreZ(nullVector3) = nullFloat .
endfm

fmod VECTOR2 is
  pr VECTOR3 .
  sort Vector2 .
  op vector2 : Float Float -> Vector2 [ctor] .

  op _-_ : Vector2 Vector2 -> Vector2 [prec 33 gather (E e)] .
  op _+_ : Vector2 Vector2 -> Vector2 [assoc comm prec 33] .
  op _*_ : Float Vector2 -> Vector2 [prec 31] .
  op distance : Vector2 Vector2 -> Float .
  op magnitude : Vector2 -> Float .
  op dot : Vector2 Vector2 -> Float .
  op normalize : Vector2 -> Vector2 .

  --- Rotate counter-clockwise a point (px, py) around another point (cx, cy) by angle in degrees
  ---              pivot    angle  point (to be rotated)
  op rotatePoint : Vector2  Float  Vector2 -> Vector2 .

  vars CX CY ANGLE PX PY C S PX2 PY2 PX3 PY3 X X2 Y Y2 Z : Float .
  vars V V2 V3 V4 V5 P P2 : Vector2 .

  eq (vector2(X, Y) + vector2(X2, Y2)) = vector2(X + X2, Y + Y2) .
  eq (vector2(X, Y) - vector2(X2, Y2)) = vector2(X - X2, Y - Y2) .
  eq (S * vector2(X, Y)) = vector2(S * X, S * Y) .
  eq magnitude(vector2(X,Y)) = sqrt(X * X + Y * Y) .
  eq distance(V, V2) = magnitude(V - V2) .
  eq dot(vector2(X, Y), vector2(X2, Y2)) = X * X2 + Y * Y2 .
  ceq normalize(vector2(X,Y)) = vector2(X / S, Y / S) 
    if S := magnitude(vector2(X,Y)) .

  ceq rotatePoint(vector2(CX,CY), ANGLE, vector2(PX,PY)) =
      vector2(PX3 + CX, PY3 + CY)
    if S := sin(degreeToRadian(ANGLE)) /\
       C := cos(degreeToRadian(ANGLE)) /\
       PX2 := PX - CX /\
       PY2 := PY - CY /\
       PX3 := PX2 * C - PY2 * S /\
       PY3 := PX2 * S + PY2 * C .

  ---                 start point  end point  direction
  op signedDistance : Vector2      Vector2    Vector2  -> Float .
  ceq signedDistance(P,P2,V) =
      if Y >= 0.0
      then X
      else -1.0 * X
      fi
    if X := distance(P,P2) /\
       Y := dot(P2 - P, V) .

  ---                  start point  end point  projection direction
  op projectDistance : Vector2      Vector2    Vector2   -> Float .
  ceq projectDistance(P,P2,V) = dot(V2,V3)
    if V2 := normalize(V) /\
       V3 := P2 - P .
  
  ---                         direction
  op longitudeComp : Vector2  Vector2   -> Float .
  op lateralComp   : Vector2  Vector2   -> Float .
  eq longitudeComp(V, V2) = projectDistance(vector2(0.0, 0.0), V, V2) .
  ceq lateralComp(V, V2) = sqrt(X * X - Y * Y) 
    if X := magnitude(V) /\
       Y := projectDistance(vector2(0.0, 0.0), V, V2) .

  op vector3To2 : Vector3 -> Vector2 .
  eq vector3To2(X Y Z) = vector2(X,Y) .
endfm

view Vector2 from TRIV to VECTOR2 is
  sort Elt to Vector2 .
endv

fmod RECT is
  pr VECTOR2 .
  pr LIST{Vector2} .
  sort Rect .
  ---       leftmost-x  bottommost-y  width  height
  op ____ : Float       Float         Float  Float -> Rect [ctor] .
  ---                 center  extent
  op rectFromBounds : Vector2 Vector2 -> Rect .

  --- ratio between the intersection (overlap) of $r1 and $r2 and
  --- the union square of r1 and r2
  op IOURatio : Rect Rect -> Float .
  op isOverlap? : Rect Rect -> Bool .
  op square : Rect -> Float .
  op intersection : Rect Rect -> Rect .

  vars X Y X2 Y2 W H W2 H2 X3 Y3 W3 H3 X4 Y4 M N : Float .
  vars XMAX YMAX X2MAX Y2MAX CX CY PX PY ANGLE ANGLE2 : Float .
  vars AX BX AY BY S1 S2 S3 S4 S0 : Float . 
  vars INTERSECTION UNION : Float .
  vars P0 P1 P2 P3 P4 P5 P6 P7 P8 : Vector2 .
  vars RECT RECT2 : Rect .

  eq rectFromBounds(vector2(CX,CY), vector2(AX,AY)) =
    CX - AX
    CY - AY
    2.0 * AX
    2.0 * AY .
  eq square(X Y W H) = W * H .
  ceq isOverlap?(X Y W H, X2 Y2 W2 H2) =
      X2MAX > X and X2 < XMAX and
      Y2MAX > Y and Y2 < YMAX
    if XMAX := X + W /\ YMAX := Y + H /\
       X2MAX := X2 + W2 /\ Y2MAX := Y2 + H2 .
  ceq intersection(X Y W H, X2 Y2 W2 H2) = 
      min(X3,X4) min(Y3,Y4) max(0.0, X3 - X4) max(0.0, Y3 - Y4)
    if isOverlap?(X Y W H, X2 Y2 W2 H2) /\
      XMAX := X + W /\ YMAX := Y + H /\
      X2MAX := X2 + W2 /\ Y2MAX := Y2 + H2 /\
      X3 := min(XMAX, X2MAX) /\
      X4 := max(X, X2) /\
      Y3 := min(YMAX, Y2MAX) /\
      Y4 := max(Y, Y2) .
  eq intersection(X Y W H, X2 Y2 W2 H2) = 0.0 0.0 0.0 0.0 [owise] .

  ceq IOURatio(X Y W H, X2 Y2 W2 H2) =
      INTERSECTION / UNION
    if isOverlap?(X Y W H, X2 Y2 W2 H2) /\
      X3 Y3 W3 H3 := intersection(X Y W H, X2 Y2 W2 H2) /\
      INTERSECTION := square(X3 Y3 W3 H3) /\
      UNION := (square(X Y W H) + square(X2 Y2 W2 H2)) - INTERSECTION .
  eq IOURatio(X Y W H, X2 Y2 W2 H2) = 0.0 [owise] .

  --- check two rects defined by two list of vertices collide
  --- the two vertice lists may be rotated
  op collision : List{Vector2} List{Vector2} -> Bool .
  eq collision(P1 P2 P3 P4,   P5 P6 P7 P8) =
      pointInRect(P1,  P5 P6 P7 P8) or
      pointInRect(P2,  P5 P6 P7 P8) or
      pointInRect(P3,  P5 P6 P7 P8) or
      pointInRect(P4,  P5 P6 P7 P8) or
      pointInRect(P5,  P1 P2 P3 P4) or
      pointInRect(P6,  P1 P2 P3 P4) or
      pointInRect(P7,  P1 P2 P3 P4) or
      pointInRect(P8,  P1 P2 P3 P4) .

  --- Check if point P is inside or on the rectangle defined by points A, B, C, D.
  --- Assumes the points A, B, C, D are given in order (clockwise or counterclockwise).
  ---                    P       A B C D
  op pointInRect : Vector2 List{Vector2} -> Bool .
  ---                    P       A B C D        signs >= 0
  op pointInRect : Vector2 List{Vector2}  Bool -> Bool .
  eq pointInRect(P0, P1 P2 P3 P4) =
      pointInRect(P0, P1 P2 P3 P4, sign-line-equ(P0, P1, P2) >= 0.0) .
  ceq pointInRect(P0, P1 P2 P3 P4, SIGN:Bool) =
      SIGN2:Bool == SIGN:Bool and
      SIGN3:Bool == SIGN:Bool and
      SIGN4:Bool == SIGN:Bool
    if SIGN2:Bool := sign-line-equ(P0, P2, P3) >= 0.0 /\
       SIGN3:Bool := sign-line-equ(P0, P3, P4) >= 0.0 /\
       SIGN4:Bool := sign-line-equ(P0, P4, P1) >= 0.0 .

  --- Suppose AB has the line equation ax+by+c=0.
  --- This func returns a*px+b*py+c, where P(px,py)
  ---                A       B       P
  op sign-line-equ : Vector2 Vector2 Vector2 -> Float .
  ceq sign-line-equ(vector2(X,Y), vector2(X2,Y2), vector2(W,H)) =
      M * (W - X) + N * (H - Y)
    if M := Y - Y2 /\
       N := X2 - X .
endfm

view Rect from TRIV to RECT is
  sort Elt to Rect .
endv
fmod RECT-AND-NULL is
  pr MAYBE{Rect} * (op maybe{Rect} to nullRect) .
endfm